project:
  type: website

website:
  title: "federicoscognamiglio_view.github.io"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/fdeloscogna
      - icon: Linkedin
        href: https://www.linkedin.com/in/federico-scognamiglio/
format:
  html:
    theme: cosmo
    css: styles.css

editor: visual

