project:
  type: website
  output-dir: docs

website:
  title: "Federico Scognamiglio"
  favicon: images/me.jpg
  #site-url: 
  page-navigation: true
  back-to-top-navigation: true
  page-footer:
    left: "© Copyright 2024 Federico Scognamiglio. CC-BY-NC 4.0."
  navbar:
    right:
      - text: "Home"
        href: index.html
      - text: Orcid
        href: https://orcid.org/0000-0002-4610-0950
      - about.qmd
      - icon: github
        href: https://github.com/fdeloscogna
      - icon: linkedin
        href: https://www.linkedin.com/in/federico-scognamiglio/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true










